#!/usr/bin/env python
import musicbrainzngs
ARTIST="Iced Earth"
TITLE="The Dark Saga"

musicbrainzngs.set_useragent("testapplication", "1.0", "grinsekatz@hotmail.com")
release_id = [item for item in musicbrainzngs.search_releases(artistname=ARTIST)["release-list"] if item["title"] == TITLE][0]["id"]
release = musicbrainzngs.get_release_by_id(release_id, includes=["recordings"])
tracklist = release["release"]["medium-list"][0]["track-list"] 
tracks = [(track["number"], track["recording"]["title"]) for track in tracklist]
tracks = sorted(tracks, key=lambda track: int(track[0]))
for track in tracks:
    print(track[1])
